<?php
declare(strict_types=1);

// MixpanelGdpr SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

MixpanelGdprUtility::setRegistrar(function (MixpanelGdprUtility $u): void {
    $u->clean = [MixpanelGdprClean::class, 'call'];
    $u->done = [MixpanelGdprDone::class, 'call'];
    $u->make_error = [MixpanelGdprMakeError::class, 'call'];
    $u->feature_add = [MixpanelGdprFeatureAdd::class, 'call'];
    $u->feature_hook = [MixpanelGdprFeatureHook::class, 'call'];
    $u->feature_init = [MixpanelGdprFeatureInit::class, 'call'];
    $u->fetcher = [MixpanelGdprFetcher::class, 'call'];
    $u->make_fetch_def = [MixpanelGdprMakeFetchDef::class, 'call'];
    $u->make_context = [MixpanelGdprMakeContext::class, 'call'];
    $u->make_options = [MixpanelGdprMakeOptions::class, 'call'];
    $u->make_request = [MixpanelGdprMakeRequest::class, 'call'];
    $u->make_response = [MixpanelGdprMakeResponse::class, 'call'];
    $u->make_result = [MixpanelGdprMakeResult::class, 'call'];
    $u->make_point = [MixpanelGdprMakePoint::class, 'call'];
    $u->make_spec = [MixpanelGdprMakeSpec::class, 'call'];
    $u->make_url = [MixpanelGdprMakeUrl::class, 'call'];
    $u->param = [MixpanelGdprParam::class, 'call'];
    $u->prepare_auth = [MixpanelGdprPrepareAuth::class, 'call'];
    $u->prepare_body = [MixpanelGdprPrepareBody::class, 'call'];
    $u->prepare_headers = [MixpanelGdprPrepareHeaders::class, 'call'];
    $u->prepare_method = [MixpanelGdprPrepareMethod::class, 'call'];
    $u->prepare_params = [MixpanelGdprPrepareParams::class, 'call'];
    $u->prepare_path = [MixpanelGdprPreparePath::class, 'call'];
    $u->prepare_query = [MixpanelGdprPrepareQuery::class, 'call'];
    $u->graphql_body = [MixpanelGdprGraphql::class, 'body'];
    $u->graphql_errors = [MixpanelGdprGraphql::class, 'errors'];
    $u->result_basic = [MixpanelGdprResultBasic::class, 'call'];
    $u->result_body = [MixpanelGdprResultBody::class, 'call'];
    $u->result_headers = [MixpanelGdprResultHeaders::class, 'call'];
    $u->transform_request = [MixpanelGdprTransformRequest::class, 'call'];
    $u->transform_response = [MixpanelGdprTransformResponse::class, 'call'];
});
